


###################### @@@@ get_Zscore_CRW.r ########################

# Author : lucas villard
# Last revised : jan 28 2025
# Usage : calculate  the deviance (aka "zscores") between the collection of autocorrelation values from a CRW and the observed autocorrelation (from GPS fixes)
# 	  Z-scores can be calculated in different manners (see input parameters)

### ---Input---
# - the dataframe output from the "compute_fractal_observed_and_simulated_path.py". Both observed and simulated_CRW. They are automatically searched when you specify 
#   the animalName and deerYear in the "** input parameters** " section and will produce error if it cannot find them
# - the fractal statistic you want to calculate Z-score on (by default it's the autocorrelation)
# - the way to calculate Z-score ("traditional" is the equation of z-score published elsewhere, "up-quantile" is the positive deviance from the 95% quantile of the CRW
#   distribution, "max" and "absolute" are still under development
# - "lowThr" and "upThr" are the boundaries of stepSize you want to analyze. if you have only 100 stepSizes as generated by default in the fractal script
#    you can keep it by default but sometimes for small stepSizes (i.e less than 300 for the redDeer), it is meaningless to calculate z-score so
#    you can drop them
### --output ---
## a dataframe similar to the input, but added with the "z-score" column and filtered according to the candidate stepSizes models :
###  - "classic" will return the stepSizes models above the 95% quantile of the z-score distribution
###  - "up_quantile" will return every stepSizes models with positive z-scores 

###################################################################



#####  ** input parameters ** ######
selectedDeer<-"20074"
selectedYear<-"deerYear_2011-2012_denoised"
nbScale=2000
nbSim=100
fractalParameter<-"autocorrelation"
lowThr<-300 
upThr<-Inf
zScoreMethod<-"classic" ## "classic", "up-quantile" ("max" and  "absolute" not yet implemented)
#############################


############### * PACKAGES, FUNCTIONS AND WORKDIR * #########################

require(trajr)
require(gdata)
require(tidyverse)
require(gridExtra)
require(ggrepel)
require(ggplot2)
library(FSA)
library(ggpubr)
library(factoextra)
library(FactoMineR)
library(multcompView)
coordSplit<-function(x){
  tmp<-unlist(strsplit(x, split=" "))
  if(any(grepl("Z", tmp))){
    coordX<-as.numeric(substring(tmp[3],2,nchar(tmp[3])))
    coordY<-as.numeric(tmp[4])
  }
  else{
    coordX<-as.numeric(substring(tmp[2],2,nchar(tmp[2])))
    coordY<-as.numeric(substring(tmp[3],1,nchar(tmp[3])-1))
  }
  return(list("coordX"=coordX, "coordY"=coordY))
}


###################################**************************************###############################################
###################################******* z-score for single deer ******############################################
###################################**************************************###############################################


simDeer<-paste0(selectedDeer,"_CRW")

obsFile<-paste0("./",selectedDeer,"/",list.files(path=paste0("./",selectedDeer),
                                                 pattern=paste0("^",selectedDeer,"_", selectedYear,"_Fractal_values_",".*",nbScale,"_scales_observed_path.csv") 
)
)
obs<-read.csv(obsFile, h=T)
simFile<-paste0("./",selectedDeer,"/",list.files(path=paste0("./",selectedDeer),
                                                 pattern=paste0("^",selectedDeer,"_", selectedYear,"_Fractal_values_",".*",nbScale,"_scales_",nbSim,"_simulations.csv")
)
)
  sim<-read.csv(simFile, h=T)

  m.sim<-aggregate(sim[,fractalParameter], list(sim$stepSize), mean)
  max.sim<-aggregate(sim[,fractalParameter], list(sim$stepSize), max)
  sd.sim<-aggregate(sim[,fractalParameter], list(sim$stepSize), sd)
  confint.sim<-aggregate(sim[,fractalParameter], list(sim$stepSize), quantile, probs=c(0.05, 0.95))
  var.sim<-aggregate(sim[,fractalParameter], list(sim$stepSize), var)
  if(nrow(m.sim)>nrow(obs)){
    m.sim<-m.sim[1:nrow(obs),]
    confint.sim<-confint.sim[1:nrow(obs),]
    sd.sim<-sd.sim[1:nrow(obs),]
    var.sim<-var.sim[1:nrow(obs),]
    max.sim<-max.sim[1:nrow(obs),]
  }else{
    obs<-obs[1:nrow(m.sim),]
  }
  
  
  sumStat.sim<-data.frame(stepSize=confint.sim$Group.1,
                          obs=obs[,fractalParameter], 
                          meanSim=m.sim$x,
                          sdSim=sd.sim$x,
                          varSim=var.sim$x,
                          lowConf=confint.sim$x[,1], 
                          upConf=confint.sim$x[,2],
                          max=max.sim$x)
  
  
  ############### z-score calculation method ########
  if(zScoreMethod=="classic"){
    
    zscore<-apply(sumStat.sim, 1, function(x) c(x["obs"]-x["meanSim"]) / c(x["sdSim"]) )
    
  }else if (zScoreMethod=="up-quantile"){
    
    zscore<-apply(sumStat.sim, 1, function(x) return(x["obs"]-x["upConf"]))
    
  }else if (zScoreMethod=="max"){
    
    zscore<-apply(sumStat.sim, 1, function(x) return(x["obs"]-x["max"]))
    
  }else{
    stop("unknown zScoreMethod parameter")
  }
  
  
  zsDF<-data.frame(prenom=rep(selectedDeer, length(zscore)),
                   deerYear=rep(selectedYear,length(zscore)),
                   stepSize=sumStat.sim$stepSize,
                   obs=sumStat.sim$obs,
                   zscore=zscore)
  
  ### thresholding : we can keep certain limits of stepSize if needed
  zsDF.thr.stepsize<-zsDF[zsDF$stepSize>=lowThr & zsDF$stepSize<upThr,]
  ### second thresholding : we keep stepSizes in function of a certain zscore values for further classifications 
  if(zScoreMethod=="classic"){
    zsDF.thr.zscore<-zsDF.thr.stepsize[which(zsDF.thr.stepsize$zscore>=quantile(zsDF.thr.stepsize$zscore, 0.95)),]
    write.csv(zsDF.thr.zscore, file=paste0("./",selectedDeer,"/",selectedDeer,"_",selectedYear,"_candidate_stepSizes_from_traditional_zscores.csv"), row.names=F)
  }else if (zScoreMethod=="up-quantile"){
    zsDF.thr.zscore<-zsDF.thr.stepsize[which(zsDF.thr.stepsize$zscore>0),]
    write.csv(zsDF.thr.zscore, file=paste0("./",selectedDeer,"/",selectedDeer,"_",selectedYear,"_candidate_stepSizes_from_upConf.csv"), row.names=F)
  }else{
    stop("unknown zScoreMethod parameter")
  }
  
  
#----------------------------------------------------------------------------------------------------------------------------------------------
# *** plot autocorrelations of oberved and simulated paths by animal *** #####

func_plot_pl2 <- function(x) seq(0, max(x), 1000)
pl2<-ggplot(aes(x=stepSize, y=obs), data=sumStat.sim)+
    geom_line(aes(color="Observed path"))+
    geom_line(aes(y=meanSim), col="black")+
    geom_ribbon(aes(ymin=lowConf, ymax=upConf, color="Simulated path (CRW)",fill="Simulated path (CRW)"),alpha=0.5)+theme_bw()+
    xlab("Divider length")+
    ylab("Autocorrelation")+
    scale_color_manual(name="Paths",breaks=c("Observed path","Simulated path (CRW)"), 
                       values=c("Observed path"="red", "Simulated path (CRW)"="blue")
                       )+
    scale_fill_manual(name="Paths",breaks=c("Observed path","Simulated path (CRW)"), 
                       values=c("Observed path"="red", "Simulated path (CRW)"="blue")
    )+guides(fill="none")+
    ggtitle(paste(selectedDeer, selectedYear, sep= " "))+
    # geom_text(data=data.frame(x=1,y=1),aes(x=min(sumStat.sim$stepSize),
    #                                        y=max(sumStat.sim$obs),
    # #               label=paste0(
    # #                            "\t mean z-score :  ", signif(mean(zscore2),4),
    # #                            "\tR² :  ", signif(rsq2,4))
    #                 label=paste0( "\tR² :  ", signif(rsq2,3))),size=8/.pt, fontface="plain")+
    scale_x_continuous(breaks = func_plot_pl2)+
    theme(plot.title = element_text(hjust=0.5, size = 8),
          axis.title=element_text(size=8, face="bold"),
          legend.text=element_text(size = 8),
          legend.title = element_blank(),
          legend.position = "top" , 
          axis.text.x = element_text(angle=45, hjust=1, vjust=1, size = 8), 
          panel.grid.major.x = element_line(linewidth = 0.7, color="grey"))
  
  #do.call("grid.arrange", list(pl1,pl2)
  yPos<-layer_scales(pl2)$y$get_limits()[2]
  xPos<-layer_scales(pl2)$x$get_limits()[1]
  
  
  #pl2<-pl2+ geom_text(data=data.frame(x=xPos,y=yPos),aes(xPos,y=yPos,label=paste0( "\tR² :  ", signif(rsq2,3))),size=8/.pt, fontface="plain", vjust=0)
  
  plot(pl2)
  
  ########## save plot ######################
  file_plot<-file.path(getwd(),selectedDeer,paste(selectedDeer, "_", selectedYear, "_autocorrelation_obs_vs_crw", ".tiff", sep=""), fsep = "/" )
  print(file_plot)

  ggsave(filename =file_plot,
         plot = pl2,
         device = "tiff",
         #width = 87, height = 58, units = "mm",
         width = 174, height = 116, units = "mm",
         dpi=600
         )
#-----------------------------------------------------------------------------------------------------------------------------------------------
  
